# version: docker version no longer required (since docker compose v2)

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on: 
      - wordpress
      - mariadb
    volumes: wordpress_db:/var/www/html
    ports:
      - "443:443"
    restart: on-failure
    networks: inception_network
    env_file:
      - .env  

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on: 
      - mariadb
    volumes: wordpress_db:/var/www/html
    restart: on-failure
    networks: inception_network
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes: maria_db:/var/lib/mysql
    restart: on-failure
    networks: inception_network
#    ports:
#      - "3306:3306"
    env_file:
      - .env

volumes:
  maria_db:
    driver: local
  
  wordpress_db:
    driver: local

networks:
  inception_network:
    driver: bridge