FROM debian::bookworm

RUN apt-update -y && apt upgrade -y && apt-get install -y nginx

#create SSL dir
RUN

#generate self-signed SSL certificate
RUN

#copy nginx certificate
COPY

EXPOSE 443

CMD ["nginx", "-g", "deamon off;"]